channels:
- conda-forge
# Jupyter
- jupyterlab=3.2
- jupyter-offlinenotebook=0.2
- nodejs=12
- nbconvert=6
# Python Kernel
- ipykernel=5.1
- matplotlib=3.1
- pandas=1
- python=3.7
- scikit-image=0.15
- scikit-learn=0.21
- sympy=1.4
- pyyaml
- jupyter-gmaps

